/** Design tokens from stitch_interrupt_voice_ai_agent/interrupt_audio_lab/DESIGN.md. */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#10131c",
        "on-background": "#e0e2ef",
        surface: "#10131c",
        "surface-dim": "#10131c",
        "surface-bright": "#363943",
        "surface-container-lowest": "#0b0e17",
        "surface-container-low": "#181b25",
        "surface-container": "#1c1f29",
        "surface-container-high": "#272a33",
        "surface-container-highest": "#32343e",
        "surface-variant": "#32343e",
        "surface-tint": "#4cd7f6",
        "on-surface": "#e0e2ef",
        "on-surface-variant": "#bcc9cd",
        "inverse-surface": "#e0e2ef",
        "inverse-on-surface": "#2d303a",
        outline: "#869397",
        "outline-variant": "#3d494c",
        primary: "#4cd7f6",
        "on-primary": "#003640",
        "primary-container": "#06b6d4",
        "on-primary-container": "#00424f",
        "inverse-primary": "#00687a",
        "primary-fixed": "#acedff",
        "primary-fixed-dim": "#4cd7f6",
        "on-primary-fixed": "#001f26",
        "on-primary-fixed-variant": "#004e5c",
        secondary: "#ffb95f",
        "on-secondary": "#472a00",
        "secondary-container": "#ee9800",
        "on-secondary-container": "#5b3800",
        "secondary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#ffb95f",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        tertiary: "#d0bcff",
        "on-tertiary": "#3c0091",
        "tertiary-container": "#b395ff",
        "on-tertiary-container": "#4900ae",
        "tertiary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#23005c",
        "on-tertiary-fixed-variant": "#5516be",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        gutter: "0.75rem",
        "gutter-desktop": "1rem",
        margin: "1rem",
        "margin-desktop": "1.5rem",
      },
      fontFamily: {
        "headline-xl": ["Geist", "sans-serif"],
        "headline-xl-mobile": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "code-lg": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "metric-display": ["JetBrains Mono", "monospace"],
        "metric-unit": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "code-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "metric-display": ["28px", { lineHeight: "32px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "metric-unit": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
